# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run:  CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            CC="zig cc -target x86_64-linux" \
            CXX="zig c++ -target x86_64-linux" \go build -v -buildmode=c-shared -o out_telegram.so main.go

    - name: Upload Go results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-1.20
        path: out_telegram.so