# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install gcc-aarch64-linux-gnu
      run: sudo apt-get install gcc-aarch64-linux-gnu

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run:  CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -v -buildmode=c-shared -o out_telegram.so main.go

    - name: Upload Go results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-1.20
        path: out_telegram.so